[input]
html_selector = "article"
base_directory = "output"

[[input.files]]
path = "pages/chyba.html"
url = "/pages/chyba.html"
title = "Chyba 🐛"

[[input.files]]
path = "pages/o-mne.html"
url = "/pages/o-mne.html"
title = "O mně"

[[input.files]]
path = "mit.html"
url = "/mit.html"
title = "MIT"

[[input.files]]
path = "generovani-zvuku-zaklady.html"
url = "/generovani-zvuku-zaklady.html"
title = "Generování zvuku -- základy"

[[input.files]]
path = "site.html"
url = "/site.html"
title = "Sítě"

[[input.files]]
path = "git.html"
url = "/git.html"
title = "Git"

[[input.files]]
path = "projektove-ulohy-mit.html"
url = "/projektove-ulohy-mit.html"
title = "Projektové úlohy MIT"

[[input.files]]
path = "stm8oss.html"
url = "/stm8oss.html"
title = "Vývoj STM8 s OpenSource nástroji"

[[input.files]]
path = "deleni-v-pevne-radove-carce.html"
url = "/deleni-v-pevne-radove-carce.html"
title = "Dělení v pevné řadové čárce"

[[input.files]]
path = "dbi.html"
url = "/dbi.html"
title = "DBI"

[[input.files]]
path = "prg.html"
url = "/prg.html"
title = "PRG"

[[input.files]]
path = "psk.html"
url = "/psk.html"
title = "PSK"

[[input.files]]
path = "vscodecodium.html"
url = "/vscodecodium.html"
title = "VSCode/Codium"

[[input.files]]
path = "chocolatey.html"
url = "/chocolatey.html"
title = "Chocolatey"

[[input.files]]
path = "pip-a-venv.html"
url = "/pip-a-venv.html"
title = "pip a venv"

[[input.files]]
path = "ultrazvukovy-meric-vzdalenosti-pomoci-timeru-tim2.html"
url = "/ultrazvukovy-meric-vzdalenosti-pomoci-timeru-tim2.html"
title = "Ultrazvukový měřič vzdálenosti pomocí timeru TIM2"

[[input.files]]
path = "pouziti-casovace-jako-generatoru-pwm.html"
url = "/pouziti-casovace-jako-generatoru-pwm.html"
title = "Použití časovače jako generátoru PWM"

[[input.files]]
path = "zakladni-pouziti-casovace.html"
url = "/zakladni-pouziti-casovace.html"
title = "Základní použití časovače"

[[input.files]]
path = "cecko-pac-veci-kterych-byste-si-fakt-meli-vsimnout.html"
url = "/cecko-pac-veci-kterych-byste-si-fakt-meli-vsimnout.html"
title = "Céčko -- pác věcí, kterých byste si fakt měli všimnout"

[[input.files]]
path = "oddelena-kompilace-a-vlastni-knihovny.html"
url = "/oddelena-kompilace-a-vlastni-knihovny.html"
title = "Oddělená kompilace a vlastní knihovny"
